### ISSUE TITLE
Can't open .arsc-file - Unknown chunk type: 516

### ISSUE THREAD

**Issue by cachius** [MrIkso/ArscEditor#4]
Arsc Editor starts fine and displays the empty GUI. Then when I try to open an .arsc file through the _File -> Open_ menu it yields the following error:
```
C:\Program Files\Zulu\zulu-21\bin>java -jar C:\Temp\Downloads\ArscEditor-1.0.2-all.jar
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Unknown chunk type: 516
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:612)
        at com.mrikso.arsceditor.gui.MainWindow$1.done(MainWindow.java:165)
        at java.desktop/javax.swing.SwingWorker$4.run(SwingWorker.java:749)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
        at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
        at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
        at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
        at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: Unknown chunk type: 516
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:957)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk$Type.fromCode(Chunk.java:74)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:253)
        at com.google.devrel.gmscore.tools.apk.arsc.ChunkWithChunks.init(ChunkWithChunks.java:46)
        at com.google.devrel.gmscore.tools.apk.arsc.PackageChunk.init(PackageChunk.java:84)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:297)
        at com.google.devrel.gmscore.tools.apk.arsc.ChunkWithChunks.init(ChunkWithChunks.java:46)
        at com.google.devrel.gmscore.tools.apk.arsc.ResourceTableChunk.init(ResourceTableChunk.java:53)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:297)
        at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:241)
        at com.google.devrel.gmscore.tools.apk.arsc.BinaryResourceFile.<init>(BinaryResourceFile.java:39)
        at com.mrikso.arsceditor.gui.MainWindow$1.doInBackground(MainWindow.java:153)
        at com.mrikso.arsceditor.gui.MainWindow$1.doInBackground(MainWindow.java:148)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
Also happens with Java 8. Any ideas what's going on? A quick websearch brings up https://stackoverflow.com/questions/42936414/what-is-this-error-at-com-google-common-base-preconditions-checknotnull
https://stackoverflow.com/questions/73581017/aapt2-warning-about-unknown-chunk-type
and those apktool issues
https://github.com/iBotPeaches/Apktool/issues/3306
https://github.com/iBotPeaches/Apktool/issues/2249

The zipped arsc file in question is [com.android.managedprovisioning-34-resources.arsc.zip](https://github.com/user-attachments/files/16945669/com.android.managedprovisioning-34-resources.arsc.zip)

Kind regards

**Comment by MrIkso** [comment]
Partially fixed on 4777deb31086d607af5f66c7e5c8ac2eae16f6a0
