### ISSUE TITLE
[OPT] Rasied a NoSuchMethodException when run under jdk8

### ISSUE THREAD

**Issue by AkkaXdXd** [MrIkso/ArscEditor#8]
the issue is same for this:
https://github.com/classgraph/classgraph/issues/403

```
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at com.mrikso.arsceditor.gui.MainWindow$1.done(MainWindow.java:165)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at com.google.devrel.gmscore.tools.apk.arsc.ChunkWithChunks.init(ChunkWithChunks.java:43)
	at com.google.devrel.gmscore.tools.apk.arsc.ResourceTableChunk.init(ResourceTableChunk.java:53)
	at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:300)
	at com.google.devrel.gmscore.tools.apk.arsc.Chunk.newInstance(Chunk.java:244)
	at com.google.devrel.gmscore.tools.apk.arsc.BinaryResourceFile.<init>(BinaryResourceFile.java:39)
	at com.mrikso.arsceditor.gui.MainWindow$1.doInBackground(MainWindow.java:153)
	at com.mrikso.arsceditor.gui.MainWindow$1.doInBackground(MainWindow.java:148)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by MrIkso** [comment]
Use newer jdk. Currently jdk 8 is old. Use 11+

**Comment by AkkaXdXd** [comment]
> Use newer jdk. Currently jdk 8 is old. Use 11+

Yeah. Switch to the jdk11, the problem was gone. Thanks!
